### ISSUE TITLE
Server fails to start

### ISSUE THREAD

**Issue by johnhidey** [amiralies/coc-elixir#1]
Language server keeps shutting itself down.  Appears to be related to coc-elixir cause all the other extensions which I have installed for coc seem to work just fine.  

I have also tested with just coc-elixir installed by itself to ensure not conflicts.    

![coc-elixir](https://user-images.githubusercontent.com/2572432/60676849-ec8f5e80-9e4d-11e9-98b0-cfaaa3f1cf0f.png)

Vim version:  8.1.1244
OS: Linux Debian 9 (Stretch)
Elixir version:  1.9.0 and also tried 1.8.2

**Comment by amiralies** [comment]
Can you try manual elixir ls setup with [coc.nvim](https://github.com/neoclide/coc.nvim/wiki/Language-servers#elixir) and see if it works?

**Comment by klingberg** [comment]
I have the same issue. I can confirm that a manual setup with elixir-ls works.

**Comment by amiralies** [comment]
Ive added an option (`elixir.pathToElixirLS`) in 7b2f8cc0efd93628e81798c1f91145188b2ba6b0 to specify custom path to `elixir-ls`, build your own version of elixir ls and use this option, i think it will work.

**Comment by terenceponce** [comment]
For people who are still confused and want direct instructions on how to make this plugin work:

1. Do the following commands:

```
git clone https://github.com/JakeBecker/elixir-ls.git ~/.elixir-ls
cd ~/.elixir-ls
mix deps.get && mix compile && mix elixir_ls.release -o release
```

2. Create or update your `~/.vim/coc-settings.json` file and add this line:

```json
{
  "elixir.pathToElixirLS": "~/.elixir-ls/release/language_server.sh"
}
```

Doing the above instructions should make this plugin work with CoC.

There seems to be a problem with this plugin and the latest stable release of CoC which is why I had to do these steps on a fresh Mac.

**Comment by jordelver** [comment]
@terenceponce it would be great if these instructions were in the README.md. Could you create a quick PR? I can put a PR together if you don't have time :)

**Comment by terenceponce** [comment]
@jordelver Yeah, sure. I'll make a PR for this.

**Comment by jordelver** [comment]
Thank you
