### ISSUE TITLE
Upgrade elixir-ls

### ISSUE THREAD

**Issue by Nitrodist** [amiralies/coc-elixir#14]
There have been new releases of elixir-ls and the way this coc-elixir file works by default is to compile the v0.3.0 version. There have been patch releases after this. How about a bump to the latest version?

**Comment by amiralies** [comment]
I'll upgrade soon. Note that you can use `elixir.pathToElixirLS` option to use locally compiled elixir ls

**Comment by Nitrodist** [comment]
Yes, thanks, I followed the instructions in the README to do so and it works well, thanks :) 

If I may suggest, that instruction should be a separate heading apart from the `Troubleshooting` section - it should be under "How do I upgrade my elixir-ls version or pick my own?"
