### ISSUE TITLE
coc-elixir is not working

### ISSUE THREAD

**Issue by eddy147** [amiralies/coc-elixir#17]
_Description_
None of the features of coc-elixir in neovim are working for me.

_Reproduction steps_

- installed neovim v0.4.3
- installed coc with Plug as the only plugin as described in https://github.com/neoclide/coc.nvim
- installed coc-elixir with `:CocInstall coc-elixir`
- restart neovim, open on existing elixir project, result, see picture

![Screenshot from 2020-05-10 12-18-05](https://user-images.githubusercontent.com/1145595/81496504-5d967280-92b8-11ea-9994-ef1ad40360d8.png)

- no code completion or any elixir features available
- I also executed https://github.com/amiralies/coc-elixir#server-fails-to-start, but no change.

_My setup_
Ubuntu v18.04
neovim v0.4.3
checkhealth is OK for coc

**Comment by amiralies** [comment]
Can you pase elixir output channel logs?
`:CocCommand workspace.showOutput elixir`

**Comment by eddy147** [comment]
`[coc.nvim] Channel "elixir" not found`
ok that is at least clear there is something not right

**Comment by amiralies** [comment]
is `coc-elixir` available in `:CocList extensions` ?

**Comment by eddy147** [comment]
(Thx for your quick reaction)
Yes, attached screenshot:
![Screenshot from 2020-05-10 16-45-40](https://user-images.githubusercontent.com/1145595/81502356-be847180-92dd-11ea-8386-c557674c840b.png)

**Comment by amiralies** [comment]
Can you start server in command line ?
i.e. running `$ .config/coc/extensions/node_modules/coc-elixir/els-release/language_server.sh` shell

**Comment by eddy147** [comment]
![Screenshot from 2020-05-10 17-27-09](https://user-images.githubusercontent.com/1145595/81503369-8a13b400-92e3-11ea-9fcc-1ff564506829.png)
does this mean the server is running?

:CocCommand workspace.showOutput elixir gives the same output (channel not found)

**Comment by amiralies** [comment]
The output in shell means you can run the compiled server (which is shipping by coc-elixir) on your machine,
The only thing I can think of now is that the file type is not correct.
Try this: open your elixir file, enter `:set ft=elixir` and see if it works

**Comment by eddy147** [comment]
That seemed to do the trick!
![Screenshot from 2020-05-10 18-02-26](https://user-images.githubusercontent.com/1145595/81504241-79197180-92e8-11ea-81cb-682be367ad26.png)

Thank you so much for your time. 
One question I have left: Is it part of the coc-elixir to see syntax coloring or should I do that with a different setting/plugin?
Thx again

**Comment by amiralies** [comment]
You have to install [vim-elixir](https://github.com/elixir-editors/vim-elixir) for syntax highlights. It also fixes your filetype problem

**Comment by eddy147** [comment]
Thx so much! 👍
