### ISSUE TITLE
Is it possible to toggle(show/hide), apply/remove spec definitions ?

### ISSUE THREAD

**Issue by collegeimprovements** [amiralies/coc-elixir#19]
Thanks a lot for this extension.
It's tremendously useful.

![Screenshot 2020-05-19 at 6 53 06 PM](https://user-images.githubusercontent.com/1519705/82332363-ede45e00-9a02-11ea-95fe-79d86db695de.png)

1. Is it possible to toggle(show/hide) `spec`s  for current buffer? We can map some key-binding to it if there is any command for that.
2. Is it possible to apply those specs like `vscode` ?

**Comment by amiralies** [comment]
I'm glad people are using this.
1. There are two config for that `codeLens.enable` , `elixirLS.suggestSpecs` I'm not sure if you change them on the fly using `coc#config` or not
2. `:call CocAction('codeLensAction')`

**Comment by collegeimprovements** [comment]
Yes, I've these lines in my `coc-confi.json`.

![Screenshot 2020-05-20 at 9 18 13 AM](https://user-images.githubusercontent.com/1519705/82402750-d6e15280-9a7a-11ea-9529-68f8fc9d3242.png)


Is it anyway to make `elixirLS.suggestSpecs` - true & false (i.e. toggle) via some command like `:call CocAtion('elixirLS.suggestSpecs')` or something ? I tried this but seems like I'm doing something wrong.

**Comment by amiralies** [comment]
I think it's not possible

**Comment by collegeimprovements** [comment]
It's possible now 😊

Command: `call coc#config('codeLens', {'enable': v:true})` to show it.
`call coc#config('codeLens', {'enable': v:true})` to hide it.

I'm going to map them with some key. Thanks a lot @amiralies for this awesome coc-plugin.
