### ISSUE TITLE
Update Github Releases?

### ISSUE THREAD

**Issue by jherdman** [amiralies/coc-elixir#22]
Hi! Thank you for your work on coc-elixir. Would it be possible to update the Github releases? It helps users ascertain, at a glance, what the newest release is.

**Comment by amiralies** [comment]
Thank you.

I dont have a focus on this currently cause I'm not working actively on my elixir projects (just two small projects at work). 
I asked @axelson to transfer this repo into @elixir-lsp to gain more easy community contribution

**Comment by jherdman** [comment]
Many thanks for your efforts on coc-elixir! ❤️

**Comment by axelson** [comment]
Okay, the transfer is complete, and we are accepting volunteers to assist in maintaining the repository.

And FYI the release has been created (probably by @amiralies): https://github.com/elixir-lsp/coc-elixir/releases/tag/v0.5.0
