### ISSUE TITLE
No @spec suggestions showing up

### ISSUE THREAD

**Issue by cboggs** [amiralies/coc-elixir#9]
Hi! First, thanks so much for this extension! It's great so far!

I have noticed that I don't get any `@spec` suggestions, despite the default value of `elixirLS.suggestSpecs` being `true`, and even when I explicitly set it to `true` in my CoC config.

I don't see any errors in the ElixirLS log when I run `:CocCommand workspace.showOuptut`.

Is there a key I need to map to make them show up?

**Comment by amiralies** [comment]
set `codeLens.enable` to `true` wheter via `:CocConfig` or `:CocLocalConfig`. note that codelens requires neovim as vim doesn't support virtual texts I think.

**Comment by cboggs** [comment]
Ah, perfect! I see them showing up inline now. :-) Is there a way to accept that suggested `@spec`, or is it just something I need to copy/paste and modify?

Thanks for the quick response, too! :-)

**Comment by taiansu** [comment]
@cboggs Would you mind to elaborate on which coc-action to call? Thanks!

**Comment by amiralies** [comment]
@taiansu `:call CocAction('codeLensAction')`
